global:
  scrape_interval: 5s

rule_files:
  - "/etc/prometheus/rules/alert.rules.yml"

scrape_configs:
  - job_name: 'pedido-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
